name: DevOps / Gitleaks

on:
  pull_request:
  push:
    branches: [main, master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gitleaks:
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-gitleaks.yml@5dfbb4986ceb88f6518fa719da3a255294cf03cf
    with:
      working-directory: .
      scan-history: true
      upload-sarif: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}
