name: DevOps / Labeler

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-labeler.yml@87dcfcaf663040b8e3695e277f1979974936bfa0
    with:
      rules-json: |-
        [
          {"label": "ci", "title": "/ci/i"},
          {"label": "infra", "title": "/infra/i"}
        ]
