name: DevOps / Stale

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  stale:
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-stale.yml@5dfbb4986ceb88f6518fa719da3a255294cf03cf
    with:
      only: "both"
